/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bridge */

#ifndef _Included_bridge
#define _Included_bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bridge
 * Method:    Log
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bridge_Log
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
