/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bridge_bridge */

#ifndef _Included_bridge_bridge
#define _Included_bridge_bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bridge_bridge
 * Method:    Log
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bridge_bridge_Log
  (JNIEnv *, jclass);

/*
 * Class:     bridge_bridge
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bridge_bridge_Hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/// CAVA GENERATION
namespace bridge
{
    class bridge
    {
    }
}
